### ISSUE TITLE
Srs bio-optical database GFI CSV link broken

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#195]
first reported at  https://github.com/aodn/aodn-portal/issues/2161

Also see https://github.com/aodn/content/issues/191

**Comment by lbesnard** [comment]
Well, as far as I can tell, everything is well defined on my end.

My content ftl uses ```{my.baseurlDataServer}``` variable, defined by devs in  https://github.com/aodn/geoserver-config/blob/master/workspaces/config.ftl#L3. as **https://imos-data.s3-ap-southeast-2.amazonaws.com**

content ftl
https://github.com/aodn/geoserver-config/blob/master/workspaces/imos/JNDI_srs_oc_bodbaw/srs_oc_bodbaw_trajectory_profile_map/content.ftl#L15

So i don't quite understand how the url becomes

**https://data.aodn.org.au.s3-website-ap-southeast-2.amazonaws.com/**```IMOS/SRS/OC/BODBAW/2006_cruise-SS032006/pigment/IMOS_SRS-OC-BODBAW_X_20060331T222200Z_SS032006-pigment_END-20060409T014500Z.nc```

instead of
**https://imos-data.s3-ap-southeast-2.amazonaws.com/**IMOS/SRS/OC/BODBAW/2006_cruise-SS032006/pigment/IMOS_SRS-OC-BODBAW_X_20060331T222200Z_SS032006-pigment_END-20060409T014500Z.nc

I don't think this is a content issue, but more a 'bug' or something

**Comment by lbesnard** [comment]
@smancini , @pmbohm and @julian1 discovered an issue with chef overwriting the config.ftl geoserver file. This is now fixed

**Comment by pmbohm** [comment]
@anguss00 Whats this re-opened for?

**Comment by anguss00** [comment]
@kereid confirmed that it was still present in systest. Could you point me towards the chef PR that fixes the issue?

**Comment by lbesnard** [comment]
yeap yeap , there is a PR coming. I was on this this morning

**Comment by anguss00** [comment]
Cool, no worries @lbesnard

**Comment by pmbohm** [comment]
The original bug is gone. That is .....  the one created by config.ftl being overwritten by chef.


![screen shot 2016-04-13 at 3 20 16 pm](https://cloud.githubusercontent.com/assets/1066981/14483566/a3460cfe-018b-11e6-85ad-f7824b45f190.png)

**Comment by anguss00** [comment]
Which PR was it @pmbohm?

**Comment by lbesnard** [comment]
@kereid was right about some wrong links. doesn't matter that much though compare to bigger issues, it's fixed in a PR.

**Comment by pmbohm** [comment]
@anguss00 
https://github.com/aodn/chef-private/commit/85b8248638caf0cb5adc817b4037649a6af1bbca
A teenie typo by "The Dan"
